import React, { useState } from 'react';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import {
  Copy,
  Download,
  Check,
  ArrowUpRight,
  Cpu,
  ShieldAlert,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';
import { useAppStore } from '../lib/store';

export interface StrandsTelemetryStep {
  step: number;
  strand: string;
  action: string;
  status: string;
}

export interface StrandsPatch {
  language: string;
  target: string;
  code: string;
}

export interface StrandsData {
  framework: string;
  runtime: string;
  duration_ms: number;
  telemetry: StrandsTelemetryStep[];
  result: {
    confidence_score: number;
    risk_level: string;
    blast_radius: {
      affected_consumers: string[];
      risk_explanation: string;
    };
    patches: StrandsPatch[];
  };
}

interface FixCodeProps {
  patchSnippet?: string;
  strategy?: string;
  source?: string;
  target?: string;
  strandsData?: StrandsData | null;
}

const schemaGuardTheme: { [key: string]: React.CSSProperties } = {
  'code[class*="language-"]': {
    color: '#f4f1ec',
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '12.5px',
    lineHeight: '1.7',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    tabSize: 4,
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#f4f1ec',
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '12.5px',
    lineHeight: '1.7',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    tabSize: 4,
    hyphens: 'none',
    padding: '1.25rem',
    margin: 0,
    overflow: 'auto',
    background: '#0b0a09',
  },
  comment: { color: '#6b6660', fontStyle: 'italic' },
  punctuation: { color: '#a8a29a' },
  property: { color: '#f4f1ec' },
  tag: { color: '#ff6900' },
  boolean: { color: '#ff6900' },
  number: { color: '#ff6900', fontWeight: '500' },
  constant: { color: '#ff6900' },
  symbol: { color: '#ff6900' },
  deleted: { color: '#d94a3d', backgroundColor: 'rgba(217,74,61,0.1)' },
  inserted: { color: '#4d8c35', backgroundColor: 'rgba(77,140,53,0.1)' },
  string: { color: '#4d8c35' },
  builtin: { color: '#f4f1ec', fontWeight: '500' },
  operator: { color: '#a8a29a' },
  keyword: { color: '#ff6900', fontWeight: '600' },
  function: { color: '#f4f1ec', fontWeight: '500' },
  'class-name': { color: '#f4f1ec', fontWeight: '600' },
};

export const FixCode: React.FC<FixCodeProps> = ({
  patchSnippet = '',
  strategy = 'schema_evolution',
  source,
  target,
  strandsData,
}) => {
  const [activeTab, setActiveTab] = useState<'python' | 'typescript' | 'diff' | 'target'>('python');
  const [copied, setCopied] = useState(false);
  const [showTrace, setShowTrace] = useState(false);
  const { setToast, applyPatchToContract } = useAppStore();

  // Extract patches if generated by AWS Strands Agent
  const pythonPatch =
    strandsData?.result?.patches?.find((p) => p.language.toLowerCase() === 'python')?.code ||
    patchSnippet;

  const tsPatch =
    strandsData?.result?.patches?.find((p) => p.language.toLowerCase() === 'typescript')?.code ||
    `// Auto-synthesized Zod Remediation Shim\nimport { z } from 'zod';\n\nexport const SafeContractSchema = z.object({\n  id: z.string(),\n  accountId: z.string().optional().default('UNKNOWN'),\n  amount: z.number(),\n});`;

  const getActiveCode = () => {
    if (activeTab === 'target' && target) {
      return {
        code: target,
        lang: 'json',
        filename: 'contract.v2.json',
      };
    }

    if (activeTab === 'typescript') {
      return {
        code: tsPatch,
        lang: 'typescript',
        filename: 'adapter.schema.ts',
      };
    }

    if (activeTab === 'diff') {
      return {
        code: patchSnippet.includes('---') ? patchSnippet : `--- baseline_contract.json\n+++ candidate_contract.json\n@@ -1,4 +1,3 @@\n  "required": [\n    "id",\n-   "accountId",\n    "amount"\n  ]`,
        lang: 'diff',
        filename: 'schema_patch.diff',
      };
    }

    return {
      code: pythonPatch,
      lang: 'python',
      filename: 'models.py',
    };
  };

  const { code, lang, filename } = getActiveCode();

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setToast({
      message: `Copied ${filename} to clipboard`,
      type: 'success',
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([code], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    setToast({
      message: `Downloaded ${filename}`,
      type: 'info',
    });
  };

  const handleApply = () => {
    if (code.includes('No patch required')) {
      setToast({
        message: 'Contract is already aligned with the payload.',
        type: 'info',
      });
      return;
    }
    const patchToApply = activeTab === 'target' && target ? target : code;
    applyPatchToContract(patchToApply);
  };

  return (
    <div
      id="the-fix-section"
      className="rounded-2xl border border-[#26221d] bg-[#14120f] p-6 shadow-sm overflow-hidden"
    >
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-[#26221d]">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[11px] uppercase tracking-[0.08em] font-medium text-[#6b6660]">
              MOMENT 4 · AUTONOMOUS REMEDIATION
            </span>
            {strandsData && (
              <span className="flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-mono bg-[#ff6900]/10 text-[#ff6900] border border-[#ff6900]/25">
                <Cpu className="w-3 h-3" />
                AWS STRANDS SDK
              </span>
            )}
          </div>
          <h3 className="text-[20px] leading-[1.15] tracking-[-0.02em] font-semibold text-[#f4f1ec] mt-0.5">
            The Fix
          </h3>
          <p className="text-[13px] leading-normal text-[#6b6660]">
            Autonomous backward-compatible polyglot shims
          </p>
        </div>

        {/* Tab Controls */}
        <div className="flex items-center gap-1.5 p-1 rounded-lg bg-[#0b0a09] border border-[#26221d] flex-wrap">
          <button
            type="button"
            onClick={() => setActiveTab('python')}
            className={`px-3 py-1.5 rounded text-[12px] font-mono transition-colors ${
              activeTab === 'python'
                ? 'bg-[#1c1915] text-[#f4f1ec] border border-[#3a342c]'
                : 'text-[#6b6660] hover:text-[#a8a29a]'
            }`}
          >
            Python (Pydantic)
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('typescript')}
            className={`px-3 py-1.5 rounded text-[12px] font-mono transition-colors ${
              activeTab === 'typescript'
                ? 'bg-[#1c1915] text-[#f4f1ec] border border-[#3a342c]'
                : 'text-[#6b6660] hover:text-[#a8a29a]'
            }`}
          >
            TypeScript (Zod)
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('diff')}
            className={`px-3 py-1.5 rounded text-[12px] font-mono transition-colors ${
              activeTab === 'diff'
                ? 'bg-[#1c1915] text-[#f4f1ec] border border-[#3a342c]'
                : 'text-[#6b6660] hover:text-[#a8a29a]'
            }`}
          >
            Unified Diff
          </button>
          {target && (
            <button
              type="button"
              onClick={() => setActiveTab('target')}
              className={`px-3 py-1.5 rounded text-[12px] font-mono transition-colors ${
                activeTab === 'target'
                  ? 'bg-[#1c1915] text-[#f4f1ec] border border-[#3a342c]'
                  : 'text-[#6b6660] hover:text-[#a8a29a]'
              }`}
            >
              Target Schema
            </button>
          )}
        </div>
      </div>

      {/* Strands Telemetry & Blast Radius Strip */}
      {strandsData && (
        <div className="mt-5 space-y-3">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-3 rounded-xl bg-[#0b0a09] border border-[#26221d]">
            <div>
              <span className="text-[10px] text-[#6b6660] block font-mono uppercase">Agent Risk</span>
              <span
                className={`text-[12.5px] font-mono font-bold ${
                  strandsData.result.risk_level === 'CRITICAL' ? 'text-[#d94a3d]' : 'text-[#d99a2b]'
                }`}
              >
                {strandsData.result.risk_level}
              </span>
            </div>
            <div>
              <span className="text-[10px] text-[#6b6660] block font-mono uppercase">Confidence</span>
              <span className="text-[12.5px] font-mono font-bold text-[#4d8c35]">
                {Math.round(strandsData.result.confidence_score * 100)}%
              </span>
            </div>
            <div>
              <span className="text-[10px] text-[#6b6660] block font-mono uppercase">LPU Latency</span>
              <span className="text-[12.5px] font-mono font-bold text-[#f4f1ec]">
                {strandsData.duration_ms}ms
              </span>
            </div>
          </div>

          {/* Blast Radius Context Box */}
          <div className="p-3.5 rounded-xl bg-[#ff6900]/[0.06] border border-[#ff6900]/20 flex flex-col gap-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1.5 text-[#ff6900] text-[12px] font-medium font-mono">
                <ShieldAlert className="w-3.5 h-3.5" />
                <span>Blast Radius Assessment</span>
              </div>
              <button
                type="button"
                onClick={() => setShowTrace(!showTrace)}
                className="text-[11px] font-mono text-[#a8a29a] hover:text-[#f4f1ec] flex items-center gap-1"
              >
                <span>{showTrace ? 'Hide Trace' : 'View Strands Trace'}</span>
                {showTrace ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
              </button>
            </div>
            <p className="text-[12.5px] text-[#a8a29a] leading-relaxed">
              {strandsData.result.blast_radius.risk_explanation}
            </p>
            <div className="flex items-center gap-1.5 flex-wrap pt-1">
              <span className="text-[11px] font-mono text-[#6b6660]">Affected Consumers:</span>
              {strandsData.result.blast_radius.affected_consumers.map((consumer) => (
                <span
                  key={consumer}
                  className="px-2 py-0.5 rounded text-[11px] font-mono bg-[#14120f] border border-[#26221d] text-[#f4f1ec]"
                >
                  {consumer}
                </span>
              ))}
            </div>
          </div>

          {/* Collapsible Strands Execution Trace */}
          {showTrace && (
            <div className="p-3.5 rounded-xl bg-[#0b0a09] border border-[#26221d] space-y-2">
              <div className="text-[11px] font-mono uppercase text-[#6b6660] tracking-wider mb-1">
                Strand Execution Trace
              </div>
              {strandsData.telemetry.map((t) => (
                <div key={t.step} className="flex items-center justify-between text-[11.5px] font-mono">
                  <span className="text-[#f4f1ec] flex items-center gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-[#4d8c35]" />
                    {t.strand}
                  </span>
                  <span className="text-[#6b6660]">{t.action}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Code Editor Surface */}
      <div className="mt-5 rounded-xl border border-[#26221d] bg-[#0b0a09] overflow-hidden shadow-inner">
        <div className="px-4 py-2 border-b border-[#26221d] bg-[#14120f] flex items-center justify-between text-[11px] font-mono text-[#6b6660]">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-[#4d8c35]" />
            <span className="text-[#f4f1ec]">{filename}</span>
            <span>· {lang.toUpperCase()}</span>
          </div>
          <span>UTF-8 · Ready to commit</span>
        </div>
        <div className="max-h-90 overflow-auto">
          <SyntaxHighlighter
            language={lang}
            style={schemaGuardTheme}
            customStyle={{
              background: '#0b0a09',
              margin: 0,
              padding: '1.25rem',
              fontSize: '12.5px',
              lineHeight: '1.7',
              fontFamily: 'JetBrains Mono, monospace',
              whiteSpace: 'pre',
            }}
          >
            {code || '# No patch required: payload and contract are aligned.'}
          </SyntaxHighlighter>
        </div>
      </div>

      {/* Action Buttons Footer */}
      <div className="mt-5 pt-4 border-t border-[#26221d] flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <button
            id="copy-fix-btn"
            type="button"
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg border border-[#26221d] hover:border-[#3a342c] hover:bg-[#1c1915] text-[13px] text-[#a8a29a] hover:text-[#f4f1ec] transition-colors"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-[#4d8c35]" />
                <span className="text-[#4d8c35]">Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy</span>
              </>
            )}
          </button>

          <button
            id="download-patch-btn"
            type="button"
            onClick={handleDownload}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg border border-[#26221d] hover:border-[#3a342c] hover:bg-[#1c1915] text-[13px] text-[#a8a29a] hover:text-[#f4f1ec] transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download {filename}</span>
          </button>
        </div>

        <button
          id="apply-to-contract-btn"
          type="button"
          onClick={handleApply}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-[#ff6900]/15 hover:bg-[#ff6900]/25 border border-[#ff6900]/30 text-[13px] font-medium text-[#ff6900] transition-all"
        >
          <span>Apply to Contract</span>
          <ArrowUpRight className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
};